swagger: "2.0"
info:
  version: 2.0.0
  title: Anuvaad OpenNMT Translation system- API Contract
  description: A NMT based translation system in Indic languages
  contact:
    name: Kumar Deepak
    email: kumar.deepak@tarento.com

schemes:
  - https
produces:
  - application/json  

base_path: '/translator'

paths: 
  /translate-anuvaad:
    post:
      summary: REST API to perform translation at sentence level.
      description: This api takes a list of sentence and model id dictionary as input and outputs translation of each sentence. Supporting 25 input sentences per request.
      parameters:
         - in: body
           name: translate
           required: true
           description: List of sentences to be translated
           schema:
            $ref: '#/definitions/nmt_input'
            
      tags:
      - nmt-translation

      responses:
        200:
          description: On successful completion of the task.
          schema:
            $ref: '#/definitions/nmt_response'
        401:
          description: incorrect input data
          schema:
            $ref: '#/definitions/error_status'
        404:
          description: missing input data
          schema:
            $ref: '#/definitions/error_status'
        500:
          description: interal server/model error
          schema:
            $ref: '#/definitions/error_status'    
  

definitions:
        
  nmt_input:
    type: array
    description: A list of sentence-model_id dictionary for translation. Supporting 25 input sentences per message.
    items:
      properties:
        src:
          type: string
          description: Sentence to be translated.
        id:
          type: integer
          description: model id for performing the current translation.
      
  nmt_response:
    type: object
    properties:        
      response_body:
        type: array
        description: A list of translation response along with intermediate data
        items:
          properties:
            src:
              type: string
              description: Sentence to be translated.
            tgt: 
              type: string
              description: Output translation of above src sentence
            tagged_src:
              type: string
              description: Tagged version of src sentence, meant for keep tagging information of numbers in src.
            tagged_tgt:
              type: string
              description : Tagged version of tgt output, meant for keeping information of numbers in tgt.
            pred_score:
              type: number
              description: float value of sentence prediction score
            input_subwords:
              type: string
              description: subword information of src sentence
            output_subwords:
              type: string
              description: subword information of tgt sentence
      status:
        $ref: '#/definitions/status_obj'
  

  error_status:
    description: response for status code is not 200
    type: object
    properties:
      status:
        $ref: '#/definitions/status_obj'
  
  status_obj:
    type: object
    description: Status object with every request
    properties:
      ok:
        type: string
        enum:
          - "true"
          - "false"
      statusCode: 
        type: integer
        description: http status code
      why:
        type: string
        description: Success message or reason of failure in case of error
      errObj:
        type: string
        description: System generated failure message, available only when statusCode is not 200.   
